/** Real adapter lifecycle with upstream rendering replaced at its controller seam. */
jest.mock('../upstream/src/controller/aim',()=>({Aim:class {container:any;constructor(c:any){this.container=c}onFirst(){this.container.table.cue.aimInputs.setDisabled(false)}}}))
jest.mock('../upstream/src/controller/placeball',()=>({PlaceBall:class {container:any;constructor(c:any){this.container=c}}}))
jest.mock('../upstream/src/network/client/session',()=>({Session:{getInstance:()=>({p1type:0})}}))
jest.mock('../upstream/src/model/ball',()=>({State:{InPocket:'InPocket'}}))
import {OnlinePool} from './online'
import {maxPower} from '../upstream/src/model/physics/constants'
const endpoint='https://myxbghfbapbfffkpndwo.supabase.co/functions/v1/web-pool'
const token='a'.repeat(64)
const game=(turn=1,version=0)=>({id:'game',version,yourSeat:0,status:'active',state:{turn,status:`Player ${turn+1} to shoot.`,balls:[{id:0,x:0,y:0,pocketed:false}],ballInHand:false}})
function container(){const pos={x:0,y:0,z:0,set(x:number,y:number,z:number){Object.assign(this,{x,y,z})}};const b={id:0,pos,setStationary:jest.fn(),updateMesh:jest.fn(),ballmesh:{mesh:{visible:true},shadow:{visible:true}}};const c:any={eventQueue:[],inputQueue:[],table:{balls:[b],cueball:b,outcome:[],cue:{showHelper:jest.fn(),aim:{angle:0,power:maxPower*.6,offset:{x:.1,y:0},elevation:0},aimInputs:{setDisabled:jest.fn()}}},view:{render:jest.fn()},updateController(controller:any){this.controller=controller;controller.onFirst?.()}};return c}
let requests:any[]=[]
beforeEach(()=>{document.body.innerHTML='<div class="preview-pill"></div><button id="resetTable"></button><div id="onlineBar" hidden><span id="onlineStatus"></span><button id="onlineAction"></button><button id="resignGame"></button><button id="newOpponent"></button></div>';requests=[];Object.defineProperty(globalThis,'crypto',{configurable:true,value:{randomUUID:()=>String(Math.random())}});(globalThis as any).AbortSignal.timeout=()=>undefined})
afterEach(()=>jest.restoreAllMocks())
const response=(body:any)=>Promise.resolve({ok:true,json:async()=>body})
test('scoped online view locks opponent input and never sends an account credential',async()=>{const c=container();globalThis.fetch=jest.fn(async(url,options:any)=>{requests.push({url,options});return await response({game:game()})})as any;const online=new OnlinePool(c);await online.connect({endpoint,token,expiresAt:Date.now()/1000+3600});expect(c.controller.constructor.name).toBe('Waiting');expect(c.table.cue.aimInputs.setDisabled).toHaveBeenLastCalledWith(true);expect(requests[0].options.headers).toEqual({'Content-Type':'application/json','X-Maroon-Pool-Session':token});expect(requests[0].url).not.toContain(token);expect(document.getElementById('onlineAction')!.hidden).toBe(true);await online.disconnect()})
test('actual shot boundary submits only cue inputs, retains unknown-result nonce and restores canonical turn',async()=>{const c=container();let attempts=0;globalThis.fetch=jest.fn(async(_url,options:any)=>{const data=JSON.parse(options.body);requests.push(data);if(data.action==='active')return await response({game:game(0)});if(data.action==='turn'){if(++attempts===1)throw Error('Connection lost');return await response({game:game(1,1)})}return await response({})})as any;const online=new OnlinePool(c);await online.connect({endpoint,token,expiresAt:Date.now()/1000+3600});c.updateController(c.controller.playShot());await new Promise(r=>setTimeout(r,10));expect(document.getElementById('onlineAction')!.textContent).toBe('Retry shot');(document.getElementById('onlineAction')as HTMLButtonElement).click();await new Promise(r=>setTimeout(r,10));const turns=requests.filter(x=>x.action==='turn');expect(turns).toHaveLength(2);expect(turns[0]).toEqual(turns[1]);expect(turns[0].input).toEqual({angle:0,power:.6,offset:{x:.1,y:0},elevation:0});expect(turns[0]).not.toHaveProperty('state');expect(c.controller.constructor.name).toBe('Waiting');expect(document.getElementById('onlineStatus')!.textContent).toContain('opponent');await online.disconnect()})
test('disconnect cancels waiting search but does not resign an ongoing match',async()=>{const c=container();globalThis.fetch=jest.fn(async(_url,options:any)=>{const data=JSON.parse(options.body);requests.push(data);return await response({queue:data.action==='join'?'waiting':'cancelled'})})as any;const online=new OnlinePool(c);await online.connect({endpoint,token,expiresAt:Date.now()/1000+3600});(document.getElementById('onlineAction')as HTMLButtonElement).click();await new Promise(r=>setTimeout(r,10));await online.disconnect();const join=requests.find(x=>x.action==='join'),cancel=requests.find(x=>x.action==='cancel');expect(cancel.nonce).toBe(join.nonce);expect(requests.some(x=>x.action==='forfeit')).toBe(false)})
test('slow background cancellation cannot erase a newer foreground scope or revive old matchmaking',async()=>{const c=container();let finishCancel!:()=>void,finishJoin!:(value:any)=>void;let joins=0;globalThis.fetch=jest.fn(async(_url,options:any)=>{const data=JSON.parse(options.body);requests.push({data,token:options.headers['X-Maroon-Pool-Session']});if(data.action==='active')return await response({});if(data.action==='join'&&++joins===1)return await new Promise(resolve=>{finishJoin=resolve});if(data.action==='cancel')return await new Promise(resolve=>{finishCancel=()=>resolve({ok:true,json:async()=>({queue:'cancelled'})})});return await response({queue:'waiting'})})as any;
 const online=new OnlinePool(c);await online.connect({endpoint,token,expiresAt:Date.now()/1000+3600});(document.getElementById('onlineAction')as HTMLButtonElement).click();await new Promise(r=>setTimeout(r,0));const closing=online.disconnect();await online.connect({endpoint,token:'b'.repeat(64),expiresAt:Date.now()/1000+3600});finishJoin({ok:true,json:async()=>({game:game(0)})});finishCancel();await closing;await new Promise(r=>setTimeout(r,0));expect(document.getElementById('onlineAction')!.textContent).toBe('Find opponent');expect(document.getElementById('onlineAction')!.hidden).toBe(false);(document.getElementById('onlineAction')as HTMLButtonElement).click();await new Promise(r=>setTimeout(r,0));expect(requests.filter(x=>x.data.action==='join').at(-1).token).toBe('b'.repeat(64));globalThis.fetch=jest.fn(async()=>await response({queue:'cancelled'}))as any;await online.disconnect()})
test('selected pending invitation never searches or enables shots before explicit recipient acceptance',async()=>{const c=container(),id='11111111-1111-4111-8111-111111111111';const invitation={...game(0),id,yourSeat:1,status:'pending',players:['RoomAlias','MyAlias']};globalThis.fetch=jest.fn(async(_url,options:any)=>{const data=JSON.parse(options.body);requests.push(data);return await response({game:data.action==='accept'?{...invitation,status:'active',version:1}:invitation})})as any;const online=new OnlinePool(c);await online.connect({endpoint,token,expiresAt:Date.now()/1000+3600,gameID:id});expect(requests).toEqual([{action:'get',id}]);expect(c.controller.constructor.name).toBe('Waiting');expect(document.getElementById('onlineAction')!.textContent).toBe('Accept & play');expect(document.getElementById('onlineStatus')!.textContent).toContain('RoomAlias');(document.getElementById('onlineAction')as HTMLButtonElement).click();await new Promise(r=>setTimeout(r,10));expect(requests[1]).toEqual({action:'accept',id});expect(c.controller.constructor.name).toBe('Waiting');expect(requests.some(x=>x.action==='join')).toBe(false);await online.disconnect()})
test('a finished game invites the same opponent, retains unknown-result nonce, and waits for acceptance',async()=>{const c=container(),ended={...game(),status:'finished'},child={...game(0),id:'child',status:'pending'};let attempts=0;globalThis.fetch=jest.fn(async(_url,options:any)=>{const data=JSON.parse(options.body);requests.push(data);if(data.action==='active')return await response({game:ended});if(data.action==='rematch'){if(++attempts===1)throw Error('Lost acknowledgement');return await response({game:child})}return await response({})})as any;const online=new OnlinePool(c);await online.connect({endpoint,token,expiresAt:Date.now()/1000+3600});const button=document.getElementById('onlineAction')as HTMLButtonElement;expect(button.textContent).toBe('Invite to rematch');button.click();await new Promise(r=>setTimeout(r,10));button.click();await new Promise(r=>setTimeout(r,10));const attemptsMade=requests.filter(x=>x.action==='rematch');expect(attemptsMade).toHaveLength(2);expect(attemptsMade[0]).toEqual(attemptsMade[1]);expect(attemptsMade[0]).not.toHaveProperty('opponent');expect(button.disabled).toBe(true);expect(button.textContent).toBe('Waiting for acceptance');expect(c.controller.constructor.name).toBe('Waiting');expect(document.getElementById('resignGame')!.textContent).toBe('Cancel invitation');await online.disconnect()})
test('rematch metadata arriving without a shot version change exposes explicit acceptance',async()=>{const c=container();let calls=0;const ended={...game(),status:'finished'};globalThis.fetch=jest.fn(async(_url,options:any)=>{const data=JSON.parse(options.body);requests.push(data);if(data.action==='accept')return await response({game:{...game(0),id:'child',yourSeat:1,version:1}});return await response({game:{...ended,...(++calls>1?{rematch:{id:'child',yourSeat:1,status:'pending'}}:{})}})})as any;const online=new OnlinePool(c);await online.connect({endpoint,token,expiresAt:Date.now()/1000+3600});await (online as any).refresh();const button=document.getElementById('onlineAction')as HTMLButtonElement;expect(button.textContent).toBe('Accept rematch');expect(requests.some(x=>x.action==='accept')).toBe(false);button.click();await new Promise(r=>setTimeout(r,10));expect(requests.find(x=>x.action==='accept')).toEqual({action:'accept',id:'child'});expect(c.controller.constructor.name).toBe('Waiting');await online.disconnect()})
