begin;
set local role service_role;
do $$
declare ha text:=encode(extensions.gen_random_bytes(32),'hex');hb text:=encode(extensions.gen_random_bytes(32),'hex');hc text:=encode(extensions.gen_random_bytes(32),'hex');hd text:=encode(extensions.gen_random_bytes(32),'hex');he text:=encode(extensions.gen_random_bytes(32),'hex');a uuid;b uuid;c uuid;d uuid;e uuid;rid text;callid uuid;out jsonb;seatb uuid;seata uuid;randomid uuid;deviceid uuid:=gen_random_uuid();proof text:=encode(extensions.gen_random_bytes(32),'hex');jobid uuid;leaseid uuid;messageid uuid;inv uuid;oldinv uuid;productionid uuid:=gen_random_uuid();
begin
 if has_schema_privilege('authenticated','push_private','USAGE')or has_schema_privilege('authenticated','group_call_private','USAGE')or has_function_privilege('anon','public.member_random_gateway(text,text,jsonb)','EXECUTE')then raise exception 'Private call/push access exposed';end if;
 insert into social_private.members(token_hash,username,adult,network_hash)values(ha,'cp_a_'||substr(ha,1,8),true,ha)returning id into a;insert into social_private.guidelines_acceptances(member,version)select a,required_version from social_private.guidelines_settings;
 insert into social_private.members(token_hash,username,adult,network_hash)values(hb,'cp_b_'||substr(hb,1,8),true,hb)returning id into b;insert into social_private.guidelines_acceptances(member,version)select b,required_version from social_private.guidelines_settings;
 insert into social_private.members(token_hash,username,adult,network_hash)values(hc,'cp_c_'||substr(hc,1,8),true,hc)returning id into c;insert into social_private.guidelines_acceptances(member,version)select c,required_version from social_private.guidelines_settings;
 insert into social_private.members(token_hash,username,adult,network_hash)values(hd,'cp_d_'||substr(hd,1,8),true,hd)returning id into d;insert into social_private.guidelines_acceptances(member,version)select d,required_version from social_private.guidelines_settings;
 insert into social_private.members(token_hash,username,adult,network_hash)values(he,'cp_e_'||substr(he,1,8),true,he)returning id into e;insert into social_private.guidelines_acceptances(member,version)select e,required_version from social_private.guidelines_settings;
 out:=public.member_random_gateway('join',ha,jsonb_build_object('mode','text','instance',gen_random_uuid()));if out->>'state'<>'waiting'then raise exception 'Random queue %',out;end if;
 out:=public.member_random_gateway('join',hb,jsonb_build_object('mode','text','instance',gen_random_uuid()));randomid:=(out->>'room')::uuid;if out->>'state'<>'connected'then raise exception 'Random match %',out;end if;
 if out::text like '%'||a::text||'%'or out::text like '%'||b::text||'%'or out?'token'then raise exception 'Random account identity leaked';end if;
 out:=public.member_random_gateway('block',ha,jsonb_build_object('room',randomid));if out?'error'then raise exception 'Random block %',out;end if;
 if not social_private.blocked(a,b)or not exists(select 1 from random_private.rooms where id=randomid and ended_at is not null)then raise exception 'Random account block missing';end if;
 delete from social_private.blocks where blocker=a and blocked=b;
 out:=public.communities_gateway('create',ha,jsonb_build_object('title','Calls QA','description','Synthetic call and notification checks.','category','Friends','avatar','gold','is_public',true,'alias','Captain','member_avatar','sage','nonce',gen_random_uuid()));rid:=out->>'room_id';if rid is null then raise exception 'Group %',out;end if;
 perform public.communities_gateway('join',hb,jsonb_build_object('room_id',rid,'alias','Comet','member_avatar','sky'));
 perform public.communities_gateway('join',hc,jsonb_build_object('room_id',rid,'alias','Orbit','member_avatar','coral'));
 perform public.communities_gateway('join',hd,jsonb_build_object('room_id',rid,'alias','Nova','member_avatar','rose'));
 perform public.communities_gateway('join',he,jsonb_build_object('room_id',rid,'alias','Star','member_avatar','slate'));
 out:=public.group_call_gateway('invite',ha,jsonb_build_object('room_id',rid,'mode','video','transport','direct','nonce',gen_random_uuid()));if out->>'code'<>'consent'then raise exception 'Direct consent bypass %',out;end if;
 out:=public.group_call_gateway('invite',ha,jsonb_build_object('room_id',rid,'mode','video','transport','direct','allow_direct',true,'nonce',gen_random_uuid()));callid:=(out->'call'->>'id')::uuid;seata:=(out->'call'->>'my_seat')::uuid;if callid is null then raise exception 'Invite %',out;end if;
 out:=public.group_call_gateway('poll',hb,jsonb_build_object('room_id',rid));if out->'call'->>'joined'<>'false'or out->'call'->'signals'<>'[]'then raise exception 'Unaccepted group access';end if;
 out:=public.group_call_gateway('media',hb,jsonb_build_object('room_id',rid,'call_id',callid,'allow_direct',true));if out->>'code'<>'consent'then raise exception 'Unaccepted media';end if;
 out:=public.group_call_gateway('accept',hb,jsonb_build_object('room_id',rid,'call_id',callid,'allow_direct',true));seatb:=(out->'call'->>'my_seat')::uuid;if seatb is null then raise exception 'Accept %',out;end if;
 if out::text like '%'||a::text||'%'or out::text like '%'||b::text||'%'or out::text like '%cp_a_%'then raise exception 'Call roster leaked account';end if;
 out:=public.group_call_gateway('signal',ha,jsonb_build_object('room_id',rid,'call_id',callid,'allow_direct',true,'to',seatb,'kind','ice','payload',jsonb_build_object('candidate','synthetic'),'nonce',gen_random_uuid()));if out?'error'then raise exception 'Signal %',out;end if;
 out:=public.group_call_gateway('poll',hb,jsonb_build_object('room_id',rid,'call_id',callid));if jsonb_array_length(out->'call'->'signals')<>1 then raise exception 'Signal not delivered';end if;
 out:=public.group_call_gateway('poll',hc,jsonb_build_object('room_id',rid,'call_id',callid));if out->'call'->'signals'<>'[]'then raise exception 'Signal recipient isolation';end if;
 perform public.group_call_gateway('accept',hc,jsonb_build_object('room_id',rid,'call_id',callid,'allow_direct',true));perform public.group_call_gateway('accept',hd,jsonb_build_object('room_id',rid,'call_id',callid,'allow_direct',true));
 out:=public.group_call_gateway('accept',he,jsonb_build_object('room_id',rid,'call_id',callid,'allow_direct',true));if out->>'code'<>'full'then raise exception 'Fifth call participant admitted %',out;end if;
 perform public.group_call_gateway('end',hb,jsonb_build_object('room_id',rid,'call_id',callid));
 if not exists(select 1 from group_call_private.peers where call=callid and member=b and left_at is not null)or exists(select 1 from group_call_private.calls where id=callid and ended_at is not null)then raise exception 'Leave ended everyone';end if;
 update group_call_private.calls set ends_at=now()-interval '1 second'where id=callid;perform group_call_private.cleanup(rid);
 if exists(select 1 from group_call_private.peers where call=callid and left_at is null)then raise exception 'TTL retained capture membership';end if;
 -- Device proof, generation and queue delivery are tested without contacting Apple.
 out:=public.push_devices('register',hb,jsonb_build_object('installation_id',deviceid,'secret_hash',proof,'sequence',1,'token',repeat('1',64),'environment','sandbox'));if out->>'registered'<>'true'then raise exception 'Push register %',out;end if;
 out:=public.social_gateway('room.send',ha,jsonb_build_object('room_id',rid,'text','Synthetic private notification body','nonce',gen_random_uuid()));messageid:=(out->>'resource_id')::uuid;if messageid is null then raise exception 'Message %',out;end if;
 select id into jobid from push_private.jobs where recipient=b and reference=messageid;
 if jobid is null then raise exception 'Push event not queued';end if;
 out:=public.push_devices('register',hb,jsonb_build_object('installation_id',productionid,'secret_hash',proof,'sequence',1,'token',repeat('2',64),'environment','production'));
 out:=public.push_delivery('take','{"limit":50}');if out->'items'<>'[]'::jsonb then raise exception 'Missing environment list did not fail closed';end if;
 out:=public.push_delivery('take','{"limit":50,"environments":["sandbox"]}');
 if exists(select 1 from jsonb_array_elements(out->'items')x where x->>'environment'<>'sandbox')or exists(select 1 from push_private.deliveries where device=productionid and attempts<>0)then raise exception 'Sandbox credential leased production delivery';end if;select (x->>'lease')::uuid into leaseid from jsonb_array_elements(out->'items')x where x->>'job'=jobid::text;
 if leaseid is null then raise exception 'Push lease missing %',out;end if;
 if out::text like '%Synthetic private%'or out::text like '%'||a::text||'%'then raise exception 'Push payload privacy';end if;
 out:=public.push_delivery('complete',jsonb_build_object('job',jobid,'device',deviceid,'lease',leaseid,'status',503));if out->>'completed'<>'true'then raise exception 'Queue retry failed';end if;
 if not exists(select 1 from push_private.deliveries where job=jobid and device=deviceid and state='pending'and available_at>now())then raise exception 'Retry backoff absent';end if;
 update social_private.room_members set muted_until=now()+interval '1 hour'where member=b and room=rid;
 if push_private.deliverable((select j from push_private.jobs j where id=jobid))then raise exception 'Muted room delivered';end if;
 update social_private.room_members set muted_until=null,last_read=(select max(seq)from social_private.messages where room=rid)where member=b and room=rid;
 if push_private.deliverable((select j from push_private.jobs j where id=jobid))then raise exception 'Read message delivered';end if;
 perform public.push_devices('unregister',null,jsonb_build_object('installation_id',deviceid,'secret_hash',proof,'sequence',3));
 out:=public.push_devices('register',hb,jsonb_build_object('installation_id',deviceid,'secret_hash',proof,'sequence',2,'token',repeat('1',64),'environment','sandbox'));
 if exists(select 1 from push_private.devices where id=deviceid)then raise exception 'Delayed registration resurrected logout';end if;
 out:=public.push_devices('register',hb,jsonb_build_object('installation_id',deviceid,'secret_hash',proof,'sequence',4,'token',repeat('1',64),'environment','sandbox'));if out->>'registered'<>'true'then raise exception 'Fresh registration failed';end if;
 -- Re-inviting after a decline must not revive the old request notification.
 delete from social_private.room_members where room=rid and member=e;
 perform public.communities_gateway('invite',ha,jsonb_build_object('room_id',rid,'username','cp_e_'||substr(he,1,8)));select invitation_key into oldinv from community_private.invitations where room=rid and member=e;
 select id into jobid from push_private.jobs where recipient=e and reference=oldinv;
 perform public.communities_gateway('decline',he,jsonb_build_object('room_id',rid));update social_private.room_members set joined_at=now()-interval '2 days'where room=rid and member=e;
 perform public.communities_gateway('invite',ha,jsonb_build_object('room_id',rid,'username','cp_e_'||substr(he,1,8)));select invitation_key into inv from community_private.invitations where room=rid and member=e;
 if inv=oldinv or push_private.deliverable((select j from push_private.jobs j where id=jobid))then raise exception 'Stale invitation delivered';end if;
 update social_private.members set banned=true where id=b;
 out:=public.member_random_gateway('poll',hb);if out->>'code'<>'forbidden'then raise exception 'Account suspension bypassed random';end if;
 update social_private.members set banned=false where id=b;out:=public.social_gateway('account.delete',hb);if out?'error'then raise exception 'Delete %',out;end if;
 if exists(select 1 from push_private.devices where member=b)or exists(select 1 from random_private.member_links where member=b)then raise exception 'Account deletion retained credentials';end if;
end $$;
select 'PASS member-bound random, account blocks, group consent/capacity/scoped signals/expiry, private APNs queue, mute/read guards, delayed registration, reinvite/deletion' result;
rollback;
