begin;
do $$begin
 if has_function_privilege('anon','public.web_pool_social(text,text,jsonb)','execute')or has_function_privilege('authenticated','web_pool_private.action(text,uuid,jsonb)','execute')then raise exception 'Pool invite API exposed';end if;
end$$;
set local role service_role;
do $$
declare ha text:=encode(extensions.gen_random_bytes(32),'hex');hb text:=encode(extensions.gen_random_bytes(32),'hex');hc text:=encode(extensions.gen_random_bytes(32),'hex');a uuid;b uuid;c uuid;sa text:=encode(extensions.gen_random_bytes(32),'hex');sb text:=encode(extensions.gen_random_bytes(32),'hex');r text;anonroom text;discoveryroom text;g uuid;rematch uuid;n uuid:=gen_random_uuid();key_b uuid;key_c uuid;v jsonb;state jsonb:='{"kind":"pool","rules":"maroon-web-pool-3.0.0","turn":0,"shots":0,"winner":null}';
begin
 insert into social_private.members(token_hash,username,adult,network_hash)values(ha,'wpi_a_'||substr(ha,1,8),true,ha)returning id into a;
 insert into social_private.members(token_hash,username,adult,network_hash)values(hb,'wpi_b_'||substr(hb,1,8),true,hb)returning id into b;
 insert into social_private.members(token_hash,username,adult,network_hash)values(hc,'wpi_c_'||substr(hc,1,8),true,hc)returning id into c;
 perform public.web_pool_session(ha,sa,'create');perform public.web_pool_session(hb,sb,'create');
 insert into social_private.rooms(kind,title,anonymous)values('group','Synthetic web pool group',false)returning id into r;
 insert into community_private.communities(room,creator,nonce,description,category,is_public)values(r,a,gen_random_uuid(),'Synthetic pool invitation test','Friends',false);
 perform community_private.set_identity(r,a,'MaroonCue','maroon');perform community_private.set_identity(r,b,'GoldCue','gold');perform community_private.set_identity(r,c,'Spectator','sage');
 insert into social_private.room_members(room,member,role,status)values(r,a,'owner','accepted'),(r,b,'member','accepted'),(r,c,'member','accepted');
 select member_key into key_b from community_private.identities where room=r and member=b;select member_key into key_c from community_private.identities where room=r and member=c;
 v:=public.web_pool_social('invite',ha,jsonb_build_object('room',r,'nonce',n,'opponent_member_key',key_b,'state',state));g:=(v->'game'->>'id')::uuid;
 if g is null or v->'game'->>'status'is distinct from 'pending'or v->'game'->'players'is distinct from '["MaroonCue","GoldCue"]'::jsonb then raise exception 'Group invite/alias failed %',v;end if;
 if(select count(*)from social_private.messages where game_session_id=g)<>1 then raise exception 'Missing card';end if;
 v:=public.web_pool_social('invite',ha,jsonb_build_object('room',r,'nonce',n,'opponent_member_key',key_b,'state',state));if v->'game'->>'id'is distinct from g::text or(select count(*)from social_private.messages where game_session_id=g)<>1 then raise exception 'Invite retry duplicated';end if;
 v:=public.web_pool_social('invite',ha,jsonb_build_object('room',r,'nonce',n,'opponent_member_key',key_c,'state',state));if v->>'code'is distinct from 'conflict'then raise exception 'Recipient changed on retry';end if;
 v:=public.web_pool_social('card',hc,jsonb_build_object('id',g));if v->'invitation'->>'canOpen'is distinct from 'false'or v?'game'or v->'invitation'->'players'is distinct from '["MaroonCue","GoldCue"]'::jsonb then raise exception 'Observer card leaked %',v;end if;
 v:=public.web_pool_social('get',hc,jsonb_build_object('id',g));if v->>'code'is distinct from 'not_found'then raise exception 'Observer saw state';end if;
 v:=public.web_pool_gateway('prepare',sa,jsonb_build_object('id',g,'version',0,'nonce',gen_random_uuid(),'input','{}'::jsonb));if v->>'code'is distinct from 'conflict'then raise exception 'Unaccepted game played';end if;
 v:=public.web_pool_social('accept',ha,jsonb_build_object('id',g));if v->>'code'is distinct from 'forbidden'then raise exception 'Sender accepted';end if;
 v:=public.web_pool_social('accept',hc,jsonb_build_object('id',g));if v->>'code'is distinct from 'not_found'then raise exception 'Observer accepted';end if;
 v:=public.web_pool_social('accept',hb,jsonb_build_object('id',g));if v->'game'->>'status'is distinct from 'active'then raise exception 'Recipient acceptance failed %',v;end if;
 v:=public.web_pool_social('accept',hb,jsonb_build_object('id',g));if(v->'game'->>'version')::int<>1 then raise exception 'Accept retry advanced state';end if;
 v:=public.web_pool_gateway('forfeit',sb,jsonb_build_object('id',g));if v->'game'->>'status'is distinct from 'finished'then raise exception 'Resign failed';end if;
 n:=gen_random_uuid();v:=public.web_pool_gateway('rematch',sa,jsonb_build_object('id',g,'nonce',n,'state',state));rematch:=(v->'game'->>'id')::uuid;
 if rematch is null or rematch=g or v->'game'->>'status'is distinct from 'pending'then raise exception 'Rematch did not await consent %',v;end if;
 v:=public.web_pool_gateway('rematch',sb,jsonb_build_object('id',g,'nonce',gen_random_uuid(),'state',state));if v->'game'->>'id'is distinct from rematch::text then raise exception 'Simultaneous rematch forked';end if;
 v:=public.web_pool_gateway('get',sb,jsonb_build_object('id',g));if v->'game'->'rematch'->>'id'is distinct from rematch::text or v->'game'->'rematch'->>'yourSeat'is distinct from '1'then raise exception 'Peer did not see pending rematch';end if;
 v:=public.web_pool_gateway('accept',sb,jsonb_build_object('id',rematch));if v->'game'->>'status'is distinct from 'active'then raise exception 'Peer rematch accept failed';end if;
 update social_private.room_members set status='declined'where room=r and member=b;
 v:=public.web_pool_gateway('get',sa,jsonb_build_object('id',rematch));if v->>'code'is distinct from 'forbidden'then raise exception 'Left member game stayed accessible';end if;
 v:=public.web_pool_social('list',ha);if exists(select 1 from jsonb_array_elements(v->'games')x where x->>'id'=rematch::text)then raise exception 'Removed match stayed listed';end if;
 insert into social_private.rooms(kind,title,anonymous)values('dm','Synthetic anonymous game',true)returning id into anonroom;
 insert into social_private.room_members(room,member,status)values(anonroom,a,'accepted'),(anonroom,b,'accepted');
 v:=public.web_pool_social('invite',ha,jsonb_build_object('room',anonroom,'nonce',gen_random_uuid(),'state',state));g:=(v->'game'->>'id')::uuid;
 if g is null or v->'game'->'players'is distinct from '["Player 1","Player 2"]'::jsonb then raise exception 'Anonymous identity leaked %',v;end if;
 v:=public.web_pool_social('cancel_invite',ha,jsonb_build_object('id',g));if v->'game'->>'status'is distinct from 'declined'then raise exception 'Sender cancel failed';end if;
 insert into social_private.rooms(kind,title,meta)values('dm','Synthetic discovery game',jsonb_build_object('discovery_names',jsonb_build_object(a::text,'DiscoveryA',b::text,'DiscoveryB')))returning id into discoveryroom;
 insert into social_private.room_members(room,member,status)values(discoveryroom,a,'accepted'),(discoveryroom,b,'accepted');
 v:=public.web_pool_social('invite',ha,jsonb_build_object('room',discoveryroom,'nonce',gen_random_uuid(),'state',state));g:=(v->'game'->>'id')::uuid;
 if g is null or v->'game'->'players'is distinct from '["DiscoveryA","DiscoveryB"]'::jsonb then raise exception 'Discovery identity leaked %',v;end if;
 update web_pool_private.games set expires_at=now()-interval '1 second'where id=g;
 v:=public.web_pool_social('accept',hb,jsonb_build_object('id',g));if v->>'code'is distinct from 'conflict'then raise exception 'Expired invitation accepted';end if;
end$$;
select 'PASS pool 3 invitation nonce/recipient/alias/privacy/card isolation, pending shot denial, acceptance retries, single rematch/consent, stale membership, anonymous/discovery names, expiry and ACLs' as result;
rollback;
