begin;
set local role service_role;
do $$
declare ha text:=encode(extensions.gen_random_bytes(32),'hex');hb text:=encode(extensions.gen_random_bytes(32),'hex');a uuid;b uuid;o uuid;nonce uuid:=gen_random_uuid();p jsonb;r jsonb;r2 jsonb;aid uuid;sid uuid;att uuid;bad uuid;first_start timestamptz;last_start timestamptz;
begin
 insert into social_private.members(token_hash,username,adult,network_hash)values(ha,'plan_'||substr(ha,1,8),true,ha)returning id into a;insert into social_private.guidelines_acceptances(member,version)select a,required_version from social_private.guidelines_settings;
 insert into social_private.members(token_hash,username,adult,network_hash)values(hb,'plan_'||substr(hb,1,8),true,hb)returning id into b;insert into social_private.guidelines_acceptances(member,version)select b,required_version from social_private.guidelines_settings;
 p:=jsonb_build_object('nonce',nonce,'title','Weekly QA','place','MSC','starts',extract(epoch from '2026-10-25 10:00 America/Chicago'::timestamptz),'weeks',3,'capacity',6,'details','Synthetic rollback fixture','course','CHEM 107','approval_required',true);
 r:=public.activity_plans('series.create',ha,p);sid:=(r->>'series_id')::uuid;
 if sid is null or jsonb_array_length(r->'activity_ids')<>3 then raise exception 'Series create failed %',r;end if;
 r2:=public.activity_plans('series.create',ha,p);if r<>r2 then raise exception 'Series retry duplicated';end if;
 r2:=public.activity_plans('series.create',ha,p||jsonb_build_object('title','Changed'));if r2->>'code'<>'conflict'then raise exception 'Nonce immutable';end if;
 select min(act.starts),max(act.starts)into first_start,last_start from activity_private.occurrences occ join social_private.activities act on act.id=occ.activity where occ.series=sid;
 if (first_start at time zone 'America/Chicago')::time<>'10:00'::time or(last_start at time zone 'America/Chicago')::time<>'10:00'::time or extract(epoch from last_start-first_start)<>15*86400-23*3600 then raise exception 'DST local time shifted % %',first_start,last_start;end if;
 aid:=(r->'activity_ids'->>0)::uuid;
 if public.activity_plans('series.cancel_future',hb,jsonb_build_object('activity_id',aid))->>'code'<>'forbidden'then raise exception 'Nonhost cancelled';end if;
 if public.activity_plans('series.create',ha,p||jsonb_build_object('nonce',gen_random_uuid(),'weeks',9))->>'code'<>'invalid'then raise exception 'Unbounded series';end if;
 r2:=public.activity_plans('series.cancel_future',ha,jsonb_build_object('activity_id',aid));if r2->>'is_series'<>'true'or exists(select 1 from activity_private.occurrences occ join social_private.activities act on act.id=occ.activity where occ.series=sid and not act.cancelled)then raise exception 'Cancellation failed %',r2;end if;
 insert into social_private.organizations(name,about,status)values('Rollback org','Testing','pending')returning id into o;
 insert into social_private.organization_admins(organization,member,role)values(o,a,'owner');
 p:=jsonb_build_object('nonce',gen_random_uuid(),'organization_id',o,'title','Poster QA','place','MSC','starts',extract(epoch from now()+interval '3 days'),'capacity',20,'details','Rollback promotion');
 if public.activity_plans('promotion.create',ha,p)->>'code'<>'forbidden'then raise exception 'Pending organization published';end if;
 update social_private.organizations set status='verified'where id=o;
 if public.activity_plans('promotion.create',hb,p)->>'code'<>'forbidden'then raise exception 'Nonadmin published';end if;
 r:=public.activity_plans('promotion.create',ha,p);aid:=(r->>'activity_id')::uuid;if aid is null then raise exception 'Promotion failed %',r;end if;
 if public.activity_plans('promotion.create',ha,p)<>r then raise exception 'Promotion retry duplicates';end if;
 if public.activity_plans('promotion.create',ha,p||jsonb_build_object('title','changed'))->>'code'<>'conflict'then raise exception 'Promotion nonce mutable';end if;
 if public.activity_plans('poster.authorize',hb,jsonb_build_object('activity_id',aid))->>'code'<>'forbidden'then raise exception 'Nonadmin poster write';end if;
 r:=public.activity_plans('poster.reserve',ha,jsonb_build_object('activity_id',aid,'path',gen_random_uuid()::text||'.jpg','size',100));att:=(r->>'attachment_id')::uuid;
 r:=public.activity_plans('poster.commit',ha,jsonb_build_object('activity_id',aid,'attachment_id',att));if r->>'saved'<>'true'then raise exception 'Poster commit failed %',r;end if;
 r:=public.activity_plans('poster.read',hb,jsonb_build_object('activity_id',aid));if r->>'has_poster'<>'true'then raise exception 'Visible poster missing %',r;end if;
 insert into social_private.attachments(owner,room,kind,mime,size,path,ready)values(a,aid::text,'image','image/jpeg',100,gen_random_uuid()::text||'.jpg',true)returning id into bad;
 if public.activity_plans('poster.commit',ha,jsonb_build_object('activity_id',aid,'attachment_id',bad))->>'code'<>'forbidden'then raise exception 'Ordinary media repurposed';end if;
 insert into social_private.blocks(blocker,blocked)values(b,a);
 if public.activity_plans('poster.read',hb,jsonb_build_object('activity_id',aid))->>'code'<>'forbidden'then raise exception 'Blocked poster revealed';end if;
 delete from social_private.blocks where blocker=b and blocked=a;
 update social_private.organizations set status='pending'where id=o;
 if public.activity_plans('poster.read',hb,jsonb_build_object('activity_id',aid))->>'code'<>'forbidden'then raise exception 'Unverified poster revealed';end if;
 if has_function_privilege('anon','public.activity_plans(text,text,jsonb)','EXECUTE')or has_table_privilege('authenticated','activity_private.series','SELECT')then raise exception 'Client grants leaked';end if;
end $$;
rollback;
