begin;
set local role service_role;
do $$
declare ha text:=encode(extensions.gen_random_bytes(32),'hex');hb text:=encode(extensions.gen_random_bytes(32),'hex');hc text:=encode(extensions.gen_random_bytes(32),'hex');browser_hash text:=encode(extensions.gen_random_bytes(32),'hex');code_hash text:=encode(extensions.gen_random_bytes(32),'hex');a uuid;b uuid;c uuid;out jsonb;rid uuid;dm text;otherdm text;snapshot jsonb;jobid uuid;gameid uuid;
begin
 insert into social_private.members(token_hash,username,adult,network_hash)values(ha,'bw_a_'||substr(ha,1,8),true,ha)returning id into a;
 insert into social_private.members(token_hash,username,adult,network_hash)values(hb,'bw_b_'||substr(hb,1,8),true,hb)returning id into b;
 insert into social_private.members(token_hash,username,adult,network_hash)values(hc,'bw_c_'||substr(hc,1,8),true,hc)returning id into c;
 if has_function_privilege('authenticated','public.random_browser_gateway(text,text,jsonb)','EXECUTE')then raise exception 'Browser bridge exposed';end if;
 out:=public.random_browser_gateway('pair.create',ha,jsonb_build_object('code_hash',code_hash));if out?'error'then raise exception 'Pair create %',out;end if;
 out:=public.random_browser_gateway('pair.claim',null,jsonb_build_object('code_hash',code_hash,'token_hash',browser_hash,'network_hash',ha));if out?'error'then raise exception 'Pair claim %',out;end if;
 out:=public.random_browser_gateway('pair.claim',null,jsonb_build_object('code_hash',code_hash,'token_hash',hc,'network_hash',ha));if out->>'code'<>'invalid'then raise exception 'Pair code reusable';end if;
 out:=public.random_browser_gateway('resolve',browser_hash);if out->>'token_hash'<>ha then raise exception 'Browser account mapping';end if;
 update social_private.members set banned=true where id=a;
 out:=public.random_browser_gateway('resolve',browser_hash);if out->>'code'<>'forbidden'then raise exception 'Banned browser resolved';end if;
 update social_private.members set banned=false where id=a;
 perform public.random_browser_gateway('logout',browser_hash);
 out:=public.random_browser_gateway('resolve',browser_hash);if out->>'code'<>'unauthorized'then raise exception 'Logged out browser resolved';end if;
 perform public.member_random_gateway('join',ha,jsonb_build_object('mode','text','instance',gen_random_uuid()));
 out:=public.member_random_gateway('join',hb,jsonb_build_object('mode','text','instance',gen_random_uuid()));rid:=(out->>'room')::uuid;if rid is null then raise exception 'Matching %',out;end if;
 out:=public.member_random_gateway('continue',hc,jsonb_build_object('room',rid));if out->>'code'<>'ended'then raise exception 'Outsider continued random';end if;
 out:=public.member_random_gateway('continue',ha,jsonb_build_object('room',rid));dm:=out->>'continue_room';if dm is null then raise exception 'Continue %',out;end if;
 if out->>'continue_status'<>'pending'then raise exception 'Continue skipped acceptance';end if;
 out:=public.member_random_gateway('continue',ha,jsonb_build_object('room',rid));if out->>'continue_room'<>dm then raise exception 'Continue duplicate';end if;
 snapshot:=public.social_gateway('snapshot',hb);
 if not exists(select 1 from jsonb_array_elements(snapshot->'snapshot'->'conversations')v where v->>'id'=dm and v->>'request'='true')then raise exception 'Continuation missing from requests';end if;
 if exists(select 1 from jsonb_array_elements(snapshot->'snapshot'->'conversations')v where v->>'id'=dm and(v::text like '%bw_a_%'or v::text like '%bw_b_%'or v::text like '%'||a::text||'%'))then raise exception 'Continuation identity leaked';end if;
 out:=public.social_gateway('room.send',ha,jsonb_build_object('room_id',dm,'text','Before acceptance'));if not out?'error'then raise exception 'Continuation sends before acceptance';end if;
 out:=public.social_gateway('dm.accept',hb,jsonb_build_object('room_id',dm));if out?'error'then raise exception 'Accept continuation %',out;end if;
 out:=public.social_gateway('room.send',hb,jsonb_build_object('room_id',dm,'text','Accepted anonymous chat'));if out?'error'then raise exception 'Send continuation %',out;end if;
 snapshot:=public.social_gateway('snapshot',ha);
 if not exists(select 1 from jsonb_array_elements(snapshot->'snapshot'->'conversations')r,jsonb_array_elements(r->'messages')m where r->>'id'=dm and m->>'text'='Accepted anonymous chat'and m->>'author'='Them')then raise exception 'You/Them labels missing';end if;
 out:=public.social_gateway('dm.request',ha,jsonb_build_object('username','bw_b_'||substr(hb,1,8),'text','Named context request'));otherdm:=out->>'resource_id';if otherdm is null or otherdm=dm then raise exception 'Named request correlated anonymous room';end if;
 select id into jobid from push_private.jobs where recipient=a and room=dm and kind='message'limit 1;
 out:=public.push_devices('resolve',ha,jsonb_build_object('kind','message','reference',(select reference from push_private.jobs where id=jobid)));if out->>'roomID'<>dm then raise exception 'Authorized push route %',out;end if;
 out:=public.push_devices('resolve',hc,jsonb_build_object('kind','message','reference',(select reference from push_private.jobs where id=jobid)));if out->>'code'<>'unavailable'then raise exception 'Outsider push route';end if;
 insert into social_private.blocks(blocker,blocked)values(a,b);
 out:=public.member_random_gateway('continue',ha,jsonb_build_object('room',rid));if out->>'code'<>'forbidden'then raise exception 'Blocked continuation';end if;
 out:=public.push_devices('resolve',ha,jsonb_build_object('kind','message','reference',(select reference from push_private.jobs where id=jobid)));if out->>'code'<>'unavailable'then raise exception 'Blocked push route';end if;
end $$;
select 'PASS browser one-time scoped pairing/revocation/bans; continuation idempotency, explicit acceptance, anonymous projection, named-context separation, private push routing' result;
rollback;
