-- Transactional protocol/security regression; all accounts and content roll back.
begin;
set local role service_role;
do $$
declare ha text:=encode(extensions.gen_random_bytes(32),'hex');hb text:=encode(extensions.gen_random_bytes(32),'hex');hc text:=encode(extensions.gen_random_bytes(32),'hex');
 a uuid;b uuid;c uuid;post_id uuid;second_post uuid;secret_post uuid;poll_id uuid;option_a uuid;option_b uuid;other_option uuid;nonce_id uuid:=gen_random_uuid();payload jsonb;out jsonb;obj jsonb;bad jsonb;link text;before_count int;after_count int;
begin
 if has_table_privilege('anon','social_private.poll_votes','SELECT')or has_table_privilege('authenticated','social_private.polls','INSERT')or has_function_privilege('authenticated','social_private.poll_view(uuid,uuid)','EXECUTE')or has_function_privilege('anon','social_private.rich_post_create(uuid,uuid,jsonb)','EXECUTE')then raise exception 'Private poll storage/functions exposed';end if;
 insert into social_private.members(token_hash,username,adult,network_hash)values(ha,'poll_a_'||substr(ha,1,8),true,ha)returning id into a;
 insert into social_private.members(token_hash,username,adult,network_hash)values(hb,'poll_b_'||substr(hb,1,8),true,hb)returning id into b;
 insert into social_private.members(token_hash,username,adult,network_hash)values(hc,'poll_c_'||substr(hc,1,8),true,hc)returning id into c;
 payload:=jsonb_build_object('nonce',nonce_id,'text','','anonymous',true,'link_url',' HTTPS://Example.COM/path?q=a%2Bb#section ','tags',jsonb_build_array(' #Howdy ','STUDY','study'),'poll',jsonb_build_object('question',' Where should we study? ','options',jsonb_build_array(' Library ','Cafe'),'duration_hours',24));
 out:=public.social_gateway('post.create',ha,payload);post_id:=(out->>'resource_id')::uuid;
 if post_id is null then raise exception 'Rich post creation failed %',out;end if;
 select v into obj from jsonb_array_elements(out->'snapshot'->'posts')v where v->>'id'=post_id::text;
 if obj->>'text'<>''or obj->>'linkURL'<>'https://example.com/path?q=a%2Bb#section'or obj->'tags'<>'["howdy","study"]'::jsonb then raise exception 'Link/tag normalization or empty-body extras failed %',obj;end if;
 poll_id:=(obj->'poll'->>'id')::uuid;option_a:=(obj->'poll'->'options'->0->>'id')::uuid;option_b:=(obj->'poll'->'options'->1->>'id')::uuid;
 if obj->'poll'->>'question'<>'Where should we study?'or (obj->'poll'->>'totalVotes')::int<>0 or jsonb_typeof(obj->'poll'->'endsAt')<>'number' or (obj->'poll'->>'endsAt')::numeric not between extract(epoch from now()+interval '23 hours')and extract(epoch from now()+interval '25 hours')then raise exception 'Poll initial projection/expiry wrong %',obj;end if;
 out:=public.social_gateway('post.create',ha,payload);if out->>'resource_id'is distinct from post_id::text then raise exception 'Creation retry duplicated post %',out;end if;
 out:=public.social_gateway('post.create',ha,jsonb_set(payload,'{poll,duration_hours}','72'));if out->>'code'is distinct from 'conflict'then raise exception 'Changed poll retry accepted %',out;end if;
 out:=public.social_gateway('post.create',ha,payload||'{"link_url":"https://example.com/changed"}');if out->>'code'is distinct from 'conflict'then raise exception 'Changed link retry accepted';end if;
 out:=public.social_gateway('post.create',ha,payload||'{"tags":["other"]}');if out->>'code'is distinct from 'conflict'then raise exception 'Changed tag retry accepted';end if;
 select count(*)into before_count from social_private.posts where author=a;
 for bad in select value from jsonb_array_elements('[{}, {"tags":["study"]}, {"text":4}, {"text":"valid","link_url":{}}, {"text":"valid","tags":{}}, {"text":"valid","tags":[1]}, {"text":"valid","tags":["bad tag"]}, {"text":"valid","tags":["1","2","3","4","5","6"]}, {"poll":{}}, {"poll":{"question":"Test","options":["Only"],"duration_hours":24}}, {"poll":{"question":"Test","options":["Same"," same "],"duration_hours":24}}, {"poll":{"question":"Test","options":["a","b"],"duration_hours":48}}, {"poll":{"question":"Test","options":["a",true],"duration_hours":24}}, {"poll":{"question":"Test","options":["a","b"],"duration_hours":"24"}}]'::jsonb)loop
  out:=public.social_gateway('post.create',ha,bad);if out->>'code'is distinct from 'invalid'then raise exception 'Malformed post allowed %: %',bad,out;end if;
 end loop;
 out:=public.social_gateway('post.create',ha,jsonb_build_object('text',repeat('x',1001)));if out->>'code'is distinct from 'invalid'then raise exception 'Oversized body accepted';end if;
 foreach link in array array['javascript:alert(1)','data:text/html,test','file:///tmp/x','https://user:password@example.com/x','https://user%40example.com/x','https://example.com:99999/x','https://example.com:/x','https://example.com/path with space','https://example..com/x','https://[::::]/x','https://example.com'||chr(92)||'@evil.test','https://example.com/'||repeat('x',2048)]loop
  out:=public.social_gateway('post.create',ha,jsonb_build_object('link_url',link));if out->>'code'is distinct from 'invalid'then raise exception 'Unsafe/invalid link accepted %',link;end if;
 end loop;
 select count(*)into after_count from social_private.posts where author=a;if before_count<>after_count then raise exception 'Rejected content partially persisted';end if;
 if social_private.post_link('http://[::1]:8080/a')<>'http://[::1]:8080/a'then raise exception 'Valid bracketed address rejected';end if;
 out:=public.social_gateway('post.create',hb,'{"link_url":"https://www.tamu.edu/"}');second_post:=(out->>'resource_id')::uuid;if second_post is null then raise exception 'Link-only post failed';end if;
 out:=public.social_gateway('post.create',hb,'{"poll":{"question":"Second poll","options":["A","B","C","D"],"duration_hours":168}}');second_post:=(out->>'resource_id')::uuid;
 select id into other_option from social_private.poll_options where poll=(select id from social_private.polls where post=second_post)limit 1;
 out:=public.social_gateway('poll.vote',hc,jsonb_build_object('post_id',post_id,'option_id',other_option));if out->>'code'is distinct from 'invalid'then raise exception 'Cross-poll option allowed';end if;
 out:=public.social_gateway('poll.vote',ha,jsonb_build_object('post_id',post_id,'option_id',option_a));if out?'error'then raise exception 'Author poll vote denied %',out;end if;
 out:=public.social_gateway('poll.vote',hb,jsonb_build_object('post_id',post_id,'option_id',option_a));out:=public.social_gateway('poll.vote',hb,jsonb_build_object('post_id',post_id,'option_id',option_a));
 out:=public.social_gateway('poll.vote',hc,jsonb_build_object('post_id',post_id,'option_id',option_b));
 obj:=social_private.poll_view(b,post_id);if(obj->>'totalVotes')::int<>3 or(obj->'options'->0->>'votes')::int<>2 or obj->>'myOptionID'<>option_a::text then raise exception 'Unique vote total/own choice wrong %',obj;end if;
 out:=public.social_gateway('poll.vote',hb,jsonb_build_object('post_id',post_id,'option_id',option_b));obj:=social_private.poll_view(b,post_id);
 if(obj->>'totalVotes')::int<>3 or(obj->'options'->0->>'votes')::int<>1 or(obj->'options'->1->>'votes')::int<>2 or obj->>'myOptionID'<>option_b::text then raise exception 'Changing choice inflated counts %',obj;end if;
 if social_private.karma(a)<>0 then raise exception 'Poll participation affected karma';end if;
 if obj::text like '%'||a::text||'%'or obj::text like '%'||b::text||'%'or obj::text like '%'||c::text||'%'or obj::text like '%poll_a_%'or obj::text like '%poll_b_%'or obj::text like '%member%'then raise exception 'Voter identity leaked';end if;
 out:=public.account_controls('export',hb,'{"section":"preferences"}');if jsonb_array_length(out->'data'->'poll_votes')<>1 or out->'data'->'poll_votes'->0->>'option_id'<>option_b::text then raise exception 'Own poll vote export missing';end if;
 out:=public.account_controls('export',ha,'{"section":"posts"}');if out->'data'->0->>'link_url'<>'https://example.com/path?q=a%2Bb#section'or out->'data'->0->'poll'->>'question'<>'Where should we study?'then raise exception 'Own rich-post export missing';end if;
 out:=public.social_gateway('report',hb,jsonb_build_object('target_type','post','target_id',post_id,'reason','Synthetic poll moderation test'));
 if not exists(select 1 from social_private.reports where reporter=b and evidence->'poll'->>'question'='Where should we study?'and not(evidence->'poll'?'myOptionID'))then raise exception 'Rich post report lost content or included reporter choice';end if;
 update social_private.polls set ends_at=clock_timestamp()-interval '1 second'where id=poll_id;
 out:=public.social_gateway('poll.vote',hb,jsonb_build_object('post_id',post_id,'option_id',option_a));if out->>'code'is distinct from 'closed'then raise exception 'Vote accepted after server deadline';end if;
 update social_private.polls set ends_at=clock_timestamp()+interval '1 hour'where id=poll_id;
 update social_private.members set banned=true where id=c;
 if(social_private.poll_view(b,post_id)->>'totalVotes')::int<>2 then raise exception 'Banned voter still counted';end if;
 out:=public.social_gateway('poll.vote',hc,jsonb_build_object('post_id',post_id,'option_id',option_a));if out->>'code'is distinct from 'forbidden'then raise exception 'Banned voter admitted';end if;
 update social_private.members set banned=false where id=c;
 insert into social_private.blocks(blocker,blocked)values(b,a);
 if social_private.poll_view(b,post_id)is not null or(social_private.poll_view(a,post_id)->>'totalVotes')::int<>2 then raise exception 'Block did not hide poll/exclude blocked vote';end if;
 out:=public.social_gateway('poll.vote',hb,jsonb_build_object('post_id',post_id,'option_id',option_a));if out->>'code'is distinct from 'forbidden'then raise exception 'Blocked voter admitted';end if;
 delete from social_private.blocks where blocker=b and blocked=a;
 update social_private.members set nsfw_enabled=true where id=a;
 out:=public.social_gateway('post.create',ha,'{"community":"NSFW","poll":{"question":"Private adult poll","options":["A","B"],"duration_hours":72}}');secret_post:=(out->>'resource_id')::uuid;
 select id into other_option from social_private.poll_options where poll=(select id from social_private.polls where post=secret_post)limit 1;
 if social_private.poll_view(b,secret_post)is not null then raise exception 'Opted-out account read adult poll';end if;
 out:=public.social_gateway('poll.vote',hb,jsonb_build_object('post_id',secret_post,'option_id',other_option));if out->>'code'is distinct from 'forbidden'then raise exception 'Opted-out account voted in adult poll';end if;
 out:=public.social_gateway('account.delete',hc,'{}');if exists(select 1 from social_private.poll_votes where member=c)or(social_private.poll_view(a,post_id)->>'totalVotes')::int<>2 then raise exception 'Deleted voter retained';end if;
 out:=public.social_gateway('post.delete',ha,jsonb_build_object('post_id',post_id));
 if exists(select 1 from social_private.polls where post=post_id)or exists(select 1 from social_private.poll_votes where poll=poll_id)or exists(select 1 from social_private.posts where id=post_id and(link_url is not null or tags<>'{}'))then raise exception 'Deleted post retained poll/link/tags';end if;
 out:=public.social_gateway('poll.vote',hb,jsonb_build_object('post_id',post_id,'option_id',option_a));if out->>'code'is distinct from 'forbidden'then raise exception 'Deleted post vote accepted';end if;
 out:=public.social_gateway('post.create',ha,payload);if out->>'code'is distinct from 'conflict'then raise exception 'Deleted nonce recreated post';end if;
 out:=public.social_gateway('account.delete',ha,'{}');if exists(select 1 from social_private.polls where post=secret_post)then raise exception 'Deleted author retained poll';end if;
end $$;
select 'PASS private poll authorization, unique choices, server expiry, nonce atomicity, link/tag validation, blocks/bans, export/report and cleanup' result;
rollback;
