-- Service-only real RPC checks. Synthetic identities and every mutation roll back.
begin;
set local role service_role;
do $$
declare ha text:=encode(extensions.gen_random_bytes(32),'hex');hb text:=encode(extensions.gen_random_bytes(32),'hex');hc text:=encode(extensions.gen_random_bytes(32),'hex');hd text:=encode(extensions.gen_random_bytes(32),'hex');a uuid;b uuid;c uuid;d uuid;na text;nb text;nc text;nd text;out jsonb;payload jsonb;snap jsonb;meta jsonb;rid text;priv text;third text;code text;n uuid:=gen_random_uuid();ka uuid;kb uuid;kc uuid;otherkey uuid;inv uuid;msg text;game_id text;
begin
 if has_schema_privilege('authenticated','community_private','USAGE')or has_table_privilege('authenticated','community_private.identities','SELECT')or has_function_privilege('anon','public.communities_gateway(text,text,jsonb)','EXECUTE')then raise exception 'Private identities exposed';end if;
 na:='gid_a_'||substr(ha,1,8);nb:='gid_b_'||substr(hb,1,8);nc:='gid_c_'||substr(hc,1,8);nd:='gid_d_'||substr(hd,1,8);
 insert into social_private.members(token_hash,username,adult,network_hash)values(ha,na,true,ha)returning id into a;
 insert into social_private.members(token_hash,username,adult,network_hash)values(hb,nb,true,hb)returning id into b;
 insert into social_private.members(token_hash,username,adult,network_hash)values(hc,nc,true,hc)returning id into c;
 insert into social_private.members(token_hash,username,adult,network_hash)values(hd,nd,true,hd)returning id into d;
 payload:=jsonb_build_object('title','Identity QA '||substr(ha,1,8),'description','Synthetic public group testing.','category','Friends','avatar','gold','is_public',true,'alias','Captain','member_avatar','sage','nonce',n);
 out:=public.communities_gateway('create',ha,payload);rid:=out->>'room_id';if rid is null then raise exception 'Create: %',out;end if;
 ka:=(out->'members'->0->>'member_key')::uuid;
 out:=public.communities_gateway('create',ha,payload);if out->>'room_id' is distinct from rid then raise exception 'Create retry: %',out;end if;
 out:=public.communities_gateway('create',ha,payload||'{"title":"Changed original"}');if out->>'code' is distinct from 'conflict'then raise exception 'Nonce mismatched metadata accepted';end if;
 out:=public.communities_gateway('create',ha,payload||jsonb_build_object('nonce',gen_random_uuid(),'title','Private identity QA','is_public',false));priv:=out->>'room_id';code:=out->'community'->>'invite_code';
 if priv is null then raise exception 'Private create: %',out;end if;
 out:=public.communities_gateway('list',hb,jsonb_build_object('search',substr(ha,1,8)));if out::text like '%'||na||'%'or out::text like '%'||a::text||'%'then raise exception 'Directory account identity leak';end if;
 out:=public.communities_gateway('detail',hb,jsonb_build_object('room_id',priv));if out->>'code' is distinct from 'unavailable'then raise exception 'Private outsider detail leak';end if;
 out:=public.communities_gateway('join',hb,jsonb_build_object('room_id',rid,'alias','captain','member_avatar','gold'));if out->>'code' is distinct from 'alias_taken'then raise exception 'Case alias collision accepted %',out;end if;
 out:=public.communities_gateway('join',hb,jsonb_build_object('room_id',rid,'alias','Comet','member_avatar','sky'));if out?'error'then raise exception 'Join: %',out;end if;
 kb:=(select member_key from community_private.identities where room=rid and member=b);
 out:=public.communities_gateway('join_code',hb,jsonb_build_object('invite_code',code,'alias','DifferentComet','member_avatar','coral'));if out?'error'then raise exception 'Private code: %',out;end if;
 otherkey:=(select member_key from community_private.identities where room=priv and member=b);if otherkey=kb then raise exception 'Universal member key';end if;
 out:=public.communities_gateway('remove',ha,jsonb_build_object('room_id',rid,'member_key',otherkey));if not out?'error'then raise exception 'Foreign room key authorized removal';end if;
 out:=public.communities_gateway('invite',ha,jsonb_build_object('room_id',rid,'username',nc));if out?'error'then raise exception 'Invite %',out;end if;
 out:=public.communities_gateway('detail',ha,jsonb_build_object('room_id',rid));inv:=(out->'pending'->0->>'invitation_key')::uuid;if inv is null or out->'pending'->0->>'username'<>nc then raise exception 'Owner pending context missing';end if;
 out:=public.communities_gateway('detail',hb,jsonb_build_object('room_id',rid));if out?'pending'or out::text like '%'||nc||'%'then raise exception 'Member pending leak';end if;
 out:=public.social_gateway('room.send',ha,jsonb_build_object('room_id',rid,'text','Synthetic group message'));msg:=out->>'resource_id';if msg is null then raise exception 'Send %',out;end if;
 perform public.social_gateway('room.typing',ha,jsonb_build_object('room_id',rid));
 snap:=public.social_gateway('snapshot',hc);select e into meta from jsonb_array_elements(snap->'snapshot'->'conversationMeta')e where e->>'id'=rid;
 if meta is null or meta->>'canSend'<>'false'or meta->>'unread'<>'0'or meta->'members'<>'[]'or meta->'typing'<>'[]'then raise exception 'Pending metadata leak %',meta;end if;
 if exists(select 1 from jsonb_array_elements(snap->'snapshot'->'conversations')e where e->>'id'=rid and e->'messages'<>'[]')then raise exception 'Pending historical messages leak';end if;
 if snap::text like '%'||na||'%'or snap::text like '%'||nb||'%'or snap::text like '%'||a::text||'%'or snap::text like '%'||b::text||'%'then raise exception 'Pending identity leak';end if;
 out:=public.social_gateway('group.accept',hc,jsonb_build_object('room_id',rid));if out->>'code' is distinct from 'invalid'then raise exception 'Legacy identity bypass';end if;
 out:=public.communities_gateway('accept',hc,jsonb_build_object('room_id',rid,'alias','Orbit','member_avatar','violet'));if out?'error'then raise exception 'Accept %',out;end if;
 out:=public.communities_gateway('accept',hc,jsonb_build_object('room_id',rid,'alias','IgnoredRetryAlias','member_avatar','rose'));if out?'error'or out->'community'->>'my_alias'<>'Orbit'then raise exception 'Accept retry mutates chosen alias';end if;
 kc:=(select member_key from community_private.identities where room=rid and member=c);
 snap:=public.social_gateway('snapshot',hb);if snap::text like '%'||na||'%'or snap::text like '%'||nc||'%'or snap::text like '%'||a::text||'%'then raise exception 'Accepted snapshot account identity leak';end if;
 if not exists(select 1 from jsonb_array_elements(snap->'snapshot'->'conversations')r,jsonb_array_elements(r->'messages')m where r->>'id'=rid and m->>'id'=msg and m->>'author'='Captain')then raise exception 'Message alias missing';end if;
 out:=public.games_gateway('invite',ha,jsonb_build_object('room',rid,'kind','chess','nonce',gen_random_uuid(),'opponent_member_key',otherkey,'rules','maroon-games-2.1.0','state','{}'::jsonb));if not out?'error'then raise exception 'Foreign room game target accepted';end if;
 out:=public.games_gateway('invite',ha,jsonb_build_object('room',rid,'kind','chess','nonce',gen_random_uuid(),'opponent_member_key',kb,'rules','maroon-games-2.1.0','state','{}'::jsonb));game_id:=out->'game'->>'id';if game_id is null then raise exception 'Scoped game invite %',out;end if;
 if out::text like '%'||na||'%'or out::text like '%'||nb||'%'then raise exception 'Game players leak';end if;
 -- Ensure old generated invitations cannot expose historical account handles.
 update social_private.messages set body='@'||nb||' game invitation'where game_session_id=game_id::uuid;
 snap:=public.social_gateway('snapshot',hc);if snap::text like '%'||nb||'%'then raise exception 'Historical invitation body leaks';end if;
 out:=public.communities_gateway('remove',ha,jsonb_build_object('room_id',rid,'member_key',kb));if out?'error'then raise exception 'Remove %',out;end if;
 if social_private.can_read_room(b,rid)or social_private.can_message(b,rid)then raise exception 'Retired identity grants access';end if;
 out:=public.communities_gateway('join',hd,jsonb_build_object('room_id',rid,'alias','cOmEt','member_avatar','rose'));if out->>'code' is distinct from 'alias_taken'then raise exception 'Removed alias reused';end if;
 out:=public.games_gateway('get',hb,jsonb_build_object('id',game_id));if not out?'error'then raise exception 'Removed member accesses game';end if;
 out:=public.communities_gateway('invite',ha,jsonb_build_object('room_id',rid,'username','definitely_absent_qa'));if not out?'error'then raise exception 'Invalid invite silently succeeded';end if;
 perform public.communities_gateway('invite',ha,jsonb_build_object('room_id',rid,'username',nd));
 update social_private.room_members set joined_at=now()-interval '3 days'where room=rid and member=d;
 out:=public.communities_gateway('decline',hd,jsonb_build_object('room_id',rid));if out?'error'then raise exception 'Decline failed';end if;
 out:=public.communities_gateway('decline',hd,jsonb_build_object('room_id',rid));if out?'error'then raise exception 'Decline not idempotent';end if;
 out:=public.communities_gateway('invite',ha,jsonb_build_object('room_id',rid,'username',nd));if out->>'code' is distinct from 'rate_limit'then raise exception 'Old invitation bypassed decline cooldown %',out;end if;
 -- Transfer rechecks preexisting blocks involving the new owner.
 insert into social_private.blocks(blocker,blocked)values(c,b);
 perform public.communities_gateway('join',hb,jsonb_build_object('room_id',rid,'alias','Comet','member_avatar','sky'));
 out:=public.communities_gateway('transfer',ha,jsonb_build_object('room_id',rid,'member_key',kc));if out?'error'then raise exception 'Transfer %',out;end if;
 if social_private.can_read_room(b,rid)then raise exception 'New owner block retained member access';end if;
 perform public.communities_gateway('leave',ha,jsonb_build_object('room_id',rid));
 out:=public.communities_gateway('create',ha,payload);if out->>'code' is distinct from 'forbidden'then raise exception 'Former creator nonce leaked metadata';end if;
 -- Revocation is owner-only, scoped, retry-safe; last owner leaving revokes pending.
 perform public.communities_gateway('invite',ha,jsonb_build_object('room_id',priv,'username',nd));
 out:=public.communities_gateway('detail',ha,jsonb_build_object('room_id',priv));inv:=(out->'pending'->0->>'invitation_key')::uuid;
 out:=public.communities_gateway('revoke',hb,jsonb_build_object('room_id',priv,'invitation_key',inv));if out->>'code' is distinct from 'forbidden'then raise exception 'Member revoked invite';end if;
 out:=public.communities_gateway('revoke',ha,jsonb_build_object('room_id',priv,'invitation_key',inv));if out?'error'then raise exception 'Owner revoke failed';end if;
 out:=public.communities_gateway('revoke',ha,jsonb_build_object('room_id',priv,'invitation_key',inv));if out?'error'then raise exception 'Revoke not idempotent';end if;
 out:=public.communities_gateway('accept',hd,jsonb_build_object('room_id',priv,'alias','Denied','member_avatar','rose'));if not out?'error'then raise exception 'Revoked invitation accepted';end if;
 perform public.communities_gateway('leave',hb,jsonb_build_object('room_id',priv));
 perform public.communities_gateway('invite',ha,jsonb_build_object('room_id',priv,'username',nc));
 perform public.communities_gateway('leave',ha,jsonb_build_object('room_id',priv));
 if exists(select 1 from social_private.room_members where room=priv and status='invited')or exists(select 1 from social_private.rooms where id=priv and status='active')then raise exception 'Ownerless pending group stayed open';end if;
 out:=public.account_controls('export',hc,'{"section":"communities"}');if out::text not like '%"my_alias": "Orbit"%'or out::text like '%'||a::text||'%'then raise exception 'Own identity export %',out;end if;
 update social_private.members set banned=true where id=c;if exists(select 1 from social_private.rooms where id=rid and status='active')then raise exception 'Suspended owner group stays open';end if;
 update social_private.members set banned=false where id=c;
 out:=public.social_gateway('account.delete',hc);if out?'error'then raise exception 'Account cleanup %',out;end if;
 if exists(select 1 from community_private.identities where member=c)or exists(select 1 from community_private.invitations where member=c)then raise exception 'Deleted account identity retained';end if;
end $$;
select 'PASS group identities: service-only storage, scoped aliases/keys, pending privacy, idempotency, moderation, transfer/block/leave, games, export and deletion' result;
rollback;
