create table social_private.calls(id uuid primary key default gen_random_uuid(),room text not null references social_private.rooms on delete cascade,caller uuid not null references social_private.members on delete cascade,callee uuid not null references social_private.members on delete cascade,mode text not null check(mode in('voice','video')),transport text not null check(transport in('direct','relay')),state text not null default 'ringing'check(state in('ringing','connected','ended')),caller_direct boolean not null default false,callee_direct boolean not null default false,created_at timestamptz not null default now(),connected_at timestamptz,ended_at timestamptz,end_reason text,caller_seen timestamptz not null default now(),callee_seen timestamptz not null default now(),nonce uuid not null,unique(caller,nonce));
create index social_calls_room on social_private.calls(room,created_at desc);
create index social_calls_callee on social_private.calls(callee,state);
create table social_private.call_signals(id bigint generated always as identity primary key,call uuid not null references social_private.calls on delete cascade,sender uuid not null references social_private.members on delete cascade,kind text not null check(kind in('offer','answer','ice','media')),payload jsonb not null,created_at timestamptz not null default now());
create index social_call_signals_call on social_private.call_signals(call,id);
create index social_call_signals_sender on social_private.call_signals(sender);
alter table social_private.calls enable row level security;
alter table social_private.call_signals enable row level security;
create policy service_only on social_private.calls to service_role using(true)with check(true);
create policy service_only on social_private.call_signals to service_role using(true)with check(true);
revoke all on social_private.calls,social_private.call_signals from public,anon,authenticated;
grant all on social_private.calls,social_private.call_signals to service_role;
grant usage,select on sequence social_private.call_signals_id_seq to service_role;
create or replace function public.social_call_gateway(p_action text,p_hash text,p_input jsonb default '{}')returns jsonb language plpgsql security invoker set search_path=''as $$
declare me uuid;peer uuid;r social_private.rooms;c social_private.calls;room_id text:=p_input->>'room_id';signal_json jsonb;
begin
 me:=social_private.require_member(p_hash);
 select * into r from social_private.rooms where id=room_id;
 if r.kind is distinct from 'dm' or not social_private.can_message(me,room_id)then raise exception 'forbidden:Calls are available only in an accepted, unblocked direct conversation.';end if;
 select rm.member into peer from social_private.room_members rm join social_private.members m on m.id=rm.member where rm.room=room_id and rm.member<>me and rm.status='accepted'and not m.banned;
 if peer is null then raise exception 'forbidden:The other person is unavailable.';end if;
 -- Expire caller-specific stale sessions without a global scan on every poll.
 update social_private.calls set state='ended',ended_at=now(),end_reason='expired'where state<>'ended'and(me in(caller,callee)or peer in(caller,callee))and((state='ringing'and created_at<now()-interval '60 seconds')or(state='connected'and(least(caller_seen,callee_seen)<now()-interval '30 seconds'or connected_at<now()-interval '2 hours')));
 if p_action='invite'then
  perform pg_advisory_xact_lock(77833002);
  select * into c from social_private.calls where caller=me and nonce=(p_input->>'nonce')::uuid;
  if c.id is null then
   if exists(select 1 from social_private.calls where state<>'ended'and(me in(caller,callee)or peer in(caller,callee)))then raise exception 'busy:One of you already has an active call.';end if;
   if p_input->>'transport'='direct'and not coalesce((p_input->>'allow_direct')::boolean,false)then raise exception 'consent:Direct calls require your consent.';end if;
   if(select count(*)from social_private.calls where caller=me and created_at>now()-interval '1 minute')>=5 then raise exception 'rate_limit:Please wait before calling again.';end if;
   insert into social_private.calls(room,caller,callee,mode,transport,caller_direct,nonce)values(room_id,me,peer,p_input->>'mode',p_input->>'transport',coalesce((p_input->>'allow_direct')::boolean,false),(p_input->>'nonce')::uuid)returning * into c;
  elsif c.room<>room_id then raise exception 'conflict:That call identifier has already been used.';end if;
 else
  if p_input->>'call_id' is not null then select * into c from social_private.calls where id=(p_input->>'call_id')::uuid and room=room_id and me in(caller,callee)for no key update;
  else select * into c from social_private.calls where room=room_id and me in(caller,callee)and state<>'ended'order by created_at desc limit 1 for no key update;end if;
  if c.id is null then
   if p_action in('poll','end')then return jsonb_build_object('call',null);else raise exception 'ended:This call has ended.';end if;
  end if;
  if p_action='accept'then
   if c.state='ended'or(c.state='ringing'and c.callee<>me)then raise exception 'forbidden:This call invitation is unavailable.';end if;
   if c.transport='direct'and not coalesce((p_input->>'allow_direct')::boolean,false)then raise exception 'consent:Direct calls require your consent.';end if;
   update social_private.calls set state='connected',connected_at=coalesce(connected_at,now()),caller_seen=now(),callee_seen=now(),caller_direct=case when me=caller then coalesce((p_input->>'allow_direct')::boolean,false)else caller_direct end,callee_direct=case when me=callee then coalesce((p_input->>'allow_direct')::boolean,false)else callee_direct end where id=c.id;
  elsif p_action in('end','decline')then
   if p_action='decline'and(me<>c.callee or c.state<>'ringing')then raise exception 'forbidden:Only the recipient can decline a pending invitation.';end if;
   update social_private.calls set state='ended',ended_at=now(),end_reason=case when p_action='decline'then 'declined'else 'ended'end where id=c.id;
  elsif p_action='signal'then
   if c.state<>'connected'then raise exception 'ended:Both people must accept before connecting.';end if;
   if jsonb_typeof(p_input->'payload')<>'object'or octet_length((p_input->'payload')::text)>24000 or p_input->>'kind'not in('offer','answer','ice','media')then raise exception 'invalid:Invalid call signal.';end if;
   if(select count(*)from social_private.call_signals where call=c.id)>=1000 then raise exception 'rate_limit:Call signaling limit reached.';end if;
   insert into social_private.call_signals(call,sender,kind,payload)values(c.id,me,p_input->>'kind',p_input->'payload');
  elsif p_action not in('poll','media')then raise exception 'invalid:Unknown call action.';end if;
  update social_private.calls set caller_seen=case when caller=me then now()else caller_seen end,callee_seen=case when callee=me then now()else callee_seen end where id=c.id;
  select * into c from social_private.calls where id=c.id;
 end if;
 if p_action='media'and(c.state<>'connected'or(c.transport='direct'and not(c.caller_direct and c.callee_direct)))then raise exception 'consent:Both people must accept and consent before camera or microphone access.';end if;
 select coalesce(jsonb_agg(jsonb_build_object('id',id,'kind',kind,'payload',payload)order by id),'[]')into signal_json from(select *from social_private.call_signals where call=c.id and sender<>me and id>coalesce((p_input->>'after')::bigint,0)order by id limit 200)s;
 return jsonb_build_object('call',jsonb_build_object('id',c.id,'room_id',c.room,'mode',c.mode,'transport',c.transport,'state',c.state,'initiator',c.caller=me,'incoming',c.state='ringing'and c.callee=me,'signals',signal_json,'end_reason',c.end_reason));
exception when invalid_text_representation or check_violation or not_null_violation then return jsonb_build_object('error','Invalid call request.','code','invalid');when raise_exception then return jsonb_build_object('error',split_part(sqlerrm,':',2),'code',split_part(sqlerrm,':',1));
end $$;
revoke all on function public.social_call_gateway(text,text,jsonb)from public,anon,authenticated;
grant execute on function public.social_call_gateway(text,text,jsonb)to service_role;
select cron.schedule('social_call_cleanup','*/5 * * * *',$$ update social_private.calls set state='ended',ended_at=now(),end_reason='expired'where state<>'ended'and((state='ringing'and created_at<now()-interval '60 seconds')or(state='connected'and(least(caller_seen,callee_seen)<now()-interval '30 seconds'or connected_at<now()-interval '2 hours')));delete from social_private.calls where state='ended'and ended_at<now()-interval '1 day'; $$);

create or replace function social_private.snapshot(p_me uuid) returns jsonb language plpgsql stable security invoker set search_path='' as $$
declare result jsonb; begin
 select jsonb_build_object('username',me.username,'nsfwEnabled',me.nsfw_enabled,
 'posts',coalesce((select jsonb_agg(j order by created_at desc) from (
 select p.created_at,jsonb_build_object('id',p.id,'author',case when p.deleted or u.id is null then '[deleted]' when p.author=p_me then u.username when p.anonymous then 'Anonymous' else u.username end,'anonymous',p.anonymous,'community',p.community,'text',case when p.deleted then '[Post deleted]' else p.body end,'score',coalesce((select sum(value) from social_private.votes where post=p.id),0),'vote',coalesce((select value from social_private.votes where post=p.id and member=p_me),0),'created',extract(epoch from p.created_at),'saved',exists(select 1 from social_private.bookmarks where post=p.id and member=p_me),'acceptsDM',p.accepts_dm and not p.deleted,'deleted',p.deleted,'attachmentID',case when p.deleted then null else(select id from social_private.attachments where post=p.id and ready limit 1)end,
 'comments',coalesce((select jsonb_agg(cj order by ct) from(select c.created_at ct,jsonb_build_object('id',c.id,'author',case when c.deleted or cu.id is null then '[deleted]' when c.author=p_me then cu.username when c.anonymous then case when c.author=p.author then 'OP' else 'Aggie '||substr(md5(p.id::text||c.author::text),1,4) end else cu.username end,'text',case when c.deleted then '[Reply deleted]' else c.body end,'anonymous',c.anonymous,'created',extract(epoch from c.created_at),'isOP',c.author=p.author,'deleted',c.deleted) cj from social_private.comments c left join social_private.members cu on cu.id=c.author where c.post=p.id and not social_private.blocked(p_me,c.author) order by c.created_at limit 200) comments),'[]'))j
 from social_private.posts p left join social_private.members u on u.id=p.author where social_private.can_read_post(p_me,p.id) and not exists(select 1 from social_private.hidden h where h.member=p_me and h.post=p.id) order by p.created_at desc limit 150)posts),'[]'),
 'courses',coalesce((select jsonb_agg(r.meta) from social_private.rooms r join social_private.room_members rm on rm.room=r.id where r.kind='course' and rm.member=p_me and rm.status='accepted'),'[]'),
 'activities',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'title',a.title,'kind',a.kind,'host',case when r.meta?'organization' then (select name from social_private.organizations where id=(r.meta->>'organization')::uuid) else coalesce(u.username,'[deleted]') end,'place',a.place,'starts',extract(epoch from a.starts),'capacity',a.capacity,'details',a.details,'course',a.course,'cancelled',a.cancelled,'approvalRequired',a.approval_required,'membershipStatus',(select status from social_private.room_members where room=a.room and member=p_me),'joinRequests',case when a.host=p_me then coalesce((select jsonb_agg(mm.username) from social_private.room_members rr join social_private.members mm on mm.id=rr.member where rr.room=a.room and rr.status='pending'),'[]')else '[]'::jsonb end,'waitlisted',exists(select 1 from social_private.room_members where room=a.room and member=p_me and status='waitlisted'),'participantCount',(select count(*) from social_private.room_members where room=a.room and status='accepted'),'participants',case when exists(select 1 from social_private.room_members where room=a.room and member=p_me and status='accepted') then coalesce((select jsonb_agg(case when r.meta?'organization' and rm.role='owner' then (select name from social_private.organizations where id=(r.meta->>'organization')::uuid) else am.username end) from social_private.room_members rm join social_private.members am on am.id=rm.member where rm.room=a.room and rm.status='accepted'),'[]') else '[]'::jsonb end) order by a.starts) from social_private.activities a join social_private.rooms r on r.id=a.room left join social_private.members u on u.id=a.host where not social_private.blocked(p_me,a.host) and (not a.cancelled or a.host=p_me) and (not(r.meta?'organization') or exists(select 1 from social_private.organizations o where o.id=(r.meta->>'organization')::uuid and o.status='verified'))),'[]'),
 'conversations',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'title',case when r.kind='dm' then case when r.anonymous then 'Anonymous · post conversation' else coalesce((select u.username from social_private.room_members o join social_private.members u on u.id=o.member where o.room=r.id and o.member<>p_me limit 1),'Conversation')end else r.title end,'subtitle',case when r.status='pending' then case when r.requester=p_me then 'Request sent' else 'Message request'end else case when r.kind='course' then coalesce(r.meta->>'term','')||' · shared course room' else 'Shared '||r.kind||' conversation'end end,'messages',case when social_private.can_read_room(p_me,r.id) then social_private.message_list(p_me,r.id) else '[]'::jsonb end,'request',rm.status='invited','anonymous',r.anonymous) order by r.created_at desc) from social_private.rooms r join social_private.room_members rm on rm.room=r.id where rm.member=p_me and rm.status in('accepted','invited') and (r.kind<>'dm' or not exists(select 1 from social_private.room_members o where o.room=r.id and social_private.blocked(p_me,o.member)))),'[]'),
 'conversationMeta',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'kind',r.kind,'status',r.status,'role',rm.role,'call',case when r.kind='dm' and social_private.can_message(p_me,r.id) then(select jsonb_build_object('id',cl.id,'mode',cl.mode,'state',cl.state,'incoming',cl.callee=p_me and cl.state='ringing')from social_private.calls cl where cl.room=r.id and cl.state<>'ended'and ((cl.state='ringing'and cl.created_at>now()-interval '60 seconds')or(cl.state='connected'and least(cl.caller_seen,cl.callee_seen)>now()-interval '30 seconds'))order by cl.created_at desc limit 1)else null end,'members',case when r.kind='group' and rm.status='accepted' then coalesce((select jsonb_agg(jsonb_build_object('username',gm.username,'role',gr.role,'status',gr.status) order by gm.username) from social_private.room_members gr join social_private.members gm on gm.id=gr.member where gr.room=r.id and gr.status in('accepted','invited')),'[]')else '[]'::jsonb end,'canSend',social_private.can_message(p_me,r.id),'lastRead',rm.last_read,'pendingOutgoing',r.status='pending' and r.requester=p_me,'unread',(select count(*) from social_private.messages m where m.room=r.id and m.seq>rm.last_read and m.author<>p_me and not social_private.blocked(p_me,m.author)),'typing',coalesce((select jsonb_agg(case when r.anonymous then 'Guest' when r.meta?'organization' and t.role='owner' then(select name from social_private.organizations where id=(r.meta->>'organization')::uuid) else u.username end) from social_private.room_members t join social_private.members u on u.id=t.member where t.room=r.id and t.member<>p_me and t.typing_until>now() and not social_private.blocked(p_me,t.member)),'[]'))) from social_private.rooms r join social_private.room_members rm on rm.room=r.id where rm.member=p_me and rm.status in('accepted','invited')),'[]'),
 'ownPostIDs',coalesce((select jsonb_agg(id) from social_private.posts where author=p_me),'[]'),'ownCommentIDs',coalesce((select jsonb_agg(id) from social_private.comments where author=p_me),'[]'),'ownMessageIDs',coalesce((select jsonb_agg(id) from social_private.messages where author=p_me),'[]'),
 'attachments',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'kind',a.kind,'mime',a.mime,'size',a.size,'roomID',a.room,'messageID',a.message,'postID',a.post)) from social_private.attachments a where a.ready and ((a.post is not null and social_private.can_read_post(p_me,a.post) and exists(select 1 from social_private.posts pp where pp.id=a.post and not pp.deleted)) or(a.message is not null and social_private.can_read_room(p_me,a.room) and exists(select 1 from social_private.messages mm where mm.id=a.message and not mm.deleted and not social_private.blocked(p_me,mm.author))))),'[]'),
 'organizations',coalesce((select jsonb_agg(jsonb_build_object('id',o.id,'name',o.name,'about',o.about,'status',o.status,'followed',exists(select 1 from social_private.organization_follows where organization=o.id and member=p_me),'canManage',exists(select 1 from social_private.organization_admins where organization=o.id and member=p_me))) from social_private.organizations o where o.status='verified' or exists(select 1 from social_private.organization_admins where organization=o.id and member=p_me)),'[]'),
 'savedEvents',coalesce((select jsonb_agg(event_id) from social_private.saved_events where member=p_me),'[]')) into result from social_private.members me where me.id=p_me;
 return result;
end $$;

