create or replace function social_private.message_list(p_me uuid,p_room text) returns jsonb language sql stable security invoker set search_path='' as $$
 select coalesce(jsonb_agg(j order by seq),'[]') from (
 select m.seq,jsonb_build_object('id',m.id,'author',case when m.deleted or u.id is null then '[deleted]' when m.author=p_me then u.username when r.meta?'organization' and exists(select 1 from social_private.room_members rm where rm.room=r.id and rm.member=m.author and rm.role='owner')then(select name from social_private.organizations where id=(r.meta->>'organization')::uuid) when r.anonymous then case when m.author=p.author then 'Post author' else 'Guest' end else u.username end,'text',case when m.deleted then '[Message deleted]' else m.body end,'created',extract(epoch from m.created_at),'game',case when m.deleted then null else m.game end,'gameSessionID',case when m.deleted then null else m.game_session_id end,'replyTo',m.reply_to,'sequence',m.seq,'deleted',m.deleted,'attachmentID',case when m.deleted then null else (select id from social_private.attachments where message=m.id and ready limit 1) end,'reactions',coalesce((select jsonb_object_agg(emoji,n) from(select emoji,count(*) n from social_private.reactions where message=m.id group by emoji) reactions),'{}'),'myReactions',coalesce((select jsonb_agg(emoji) from social_private.reactions where message=m.id and member=p_me),'[]')) j
 from social_private.messages m join social_private.rooms r on r.id=m.room left join social_private.members u on u.id=m.author left join social_private.posts p on p.id=r.context_post
 where m.room=p_room and not social_private.blocked(p_me,m.author) order by m.seq desc limit 100) visible
$$;
create or replace function social_private.snapshot(p_me uuid) returns jsonb language plpgsql stable security invoker set search_path='' as $$
declare result jsonb; begin
 select jsonb_build_object('username',me.username,'nsfwEnabled',me.nsfw_enabled,
 'posts',coalesce((select jsonb_agg(j order by created_at desc) from (
 select p.created_at,jsonb_build_object('id',p.id,'author',case when p.deleted or u.id is null then '[deleted]' when p.author=p_me then u.username when p.anonymous then 'Anonymous' else u.username end,'anonymous',p.anonymous,'community',p.community,'text',case when p.deleted then '[Post deleted]' else p.body end,'score',coalesce((select sum(value) from social_private.votes where post=p.id),0),'vote',coalesce((select value from social_private.votes where post=p.id and member=p_me),0),'created',extract(epoch from p.created_at),'saved',exists(select 1 from social_private.bookmarks where post=p.id and member=p_me),'acceptsDM',p.accepts_dm and not p.deleted,'deleted',p.deleted,'attachmentID',case when p.deleted then null else(select id from social_private.attachments where post=p.id and ready limit 1)end,
 'comments',coalesce((select jsonb_agg(cj order by ct) from(select c.created_at ct,jsonb_build_object('id',c.id,'author',case when c.deleted or cu.id is null then '[deleted]' when c.author=p_me then cu.username when c.anonymous then case when c.author=p.author then 'OP' else 'Aggie '||substr(md5(p.id::text||c.author::text),1,4) end else cu.username end,'text',case when c.deleted then '[Reply deleted]' else c.body end,'anonymous',c.anonymous,'created',extract(epoch from c.created_at),'isOP',c.author=p.author,'deleted',c.deleted) cj from social_private.comments c left join social_private.members cu on cu.id=c.author where c.post=p.id and not social_private.blocked(p_me,c.author) order by c.created_at limit 200) comments),'[]'))j
 from social_private.posts p left join social_private.members u on u.id=p.author where social_private.can_read_post(p_me,p.id) and not exists(select 1 from social_private.hidden h where h.member=p_me and h.post=p.id) order by p.created_at desc limit 150)posts),'[]'),
 'courses',coalesce((select jsonb_agg(r.meta) from social_private.rooms r join social_private.room_members rm on rm.room=r.id where r.kind='course' and rm.member=p_me and rm.status='accepted'),'[]'),
 'activities',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'title',a.title,'kind',a.kind,'host',case when r.meta?'organization' then (select name from social_private.organizations where id=(r.meta->>'organization')::uuid) else coalesce(u.username,'[deleted]') end,'place',a.place,'starts',extract(epoch from a.starts),'capacity',a.capacity,'details',a.details,'course',a.course,'cancelled',a.cancelled,'approvalRequired',a.approval_required,'membershipStatus',(select status from social_private.room_members where room=a.room and member=p_me),'joinRequests',case when a.host=p_me then coalesce((select jsonb_agg(mm.username) from social_private.room_members rr join social_private.members mm on mm.id=rr.member where rr.room=a.room and rr.status='pending'),'[]')else '[]'::jsonb end,'waitlisted',exists(select 1 from social_private.room_members where room=a.room and member=p_me and status='waitlisted'),'participantCount',(select count(*) from social_private.room_members where room=a.room and status='accepted'),'participants',case when exists(select 1 from social_private.room_members where room=a.room and member=p_me and status='accepted') then coalesce((select jsonb_agg(case when r.meta?'organization' and rm.role='owner' then (select name from social_private.organizations where id=(r.meta->>'organization')::uuid) else am.username end) from social_private.room_members rm join social_private.members am on am.id=rm.member where rm.room=a.room and rm.status='accepted'),'[]') else '[]'::jsonb end) order by a.starts) from social_private.activities a join social_private.rooms r on r.id=a.room left join social_private.members u on u.id=a.host where not social_private.blocked(p_me,a.host) and (not a.cancelled or a.host=p_me) and (not(r.meta?'organization') or exists(select 1 from social_private.organizations o where o.id=(r.meta->>'organization')::uuid and o.status='verified'))),'[]'),
 'conversations',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'title',case when r.kind='dm' then case when r.anonymous then 'Anonymous · post conversation' else coalesce((select u.username from social_private.room_members o join social_private.members u on u.id=o.member where o.room=r.id and o.member<>p_me limit 1),'Conversation')end else r.title end,'subtitle',case when r.status='pending' then case when r.requester=p_me then 'Request sent' else 'Message request'end else case when r.kind='course' then coalesce(r.meta->>'term','')||' · shared course room' else 'Shared '||r.kind||' conversation'end end,'messages',case when social_private.can_read_room(p_me,r.id) then social_private.message_list(p_me,r.id) else '[]'::jsonb end,'request',rm.status='invited','anonymous',r.anonymous) order by r.created_at desc) from social_private.rooms r join social_private.room_members rm on rm.room=r.id where rm.member=p_me and rm.status in('accepted','invited') and (r.kind<>'dm' or not exists(select 1 from social_private.room_members o where o.room=r.id and social_private.blocked(p_me,o.member)))),'[]'),
 'conversationMeta',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'kind',r.kind,'status',r.status,'role',rm.role,'members',case when r.kind='group' and rm.status='accepted' then coalesce((select jsonb_agg(jsonb_build_object('username',gm.username,'role',gr.role,'status',gr.status) order by gm.username) from social_private.room_members gr join social_private.members gm on gm.id=gr.member where gr.room=r.id and gr.status in('accepted','invited')),'[]')else '[]'::jsonb end,'canSend',social_private.can_message(p_me,r.id),'lastRead',rm.last_read,'pendingOutgoing',r.status='pending' and r.requester=p_me,'unread',(select count(*) from social_private.messages m where m.room=r.id and m.seq>rm.last_read and m.author<>p_me and not social_private.blocked(p_me,m.author)),'typing',coalesce((select jsonb_agg(case when r.anonymous then 'Guest' when r.meta?'organization' and t.role='owner' then(select name from social_private.organizations where id=(r.meta->>'organization')::uuid) else u.username end) from social_private.room_members t join social_private.members u on u.id=t.member where t.room=r.id and t.member<>p_me and t.typing_until>now() and not social_private.blocked(p_me,t.member)),'[]'))) from social_private.rooms r join social_private.room_members rm on rm.room=r.id where rm.member=p_me and rm.status in('accepted','invited')),'[]'),
 'ownPostIDs',coalesce((select jsonb_agg(id) from social_private.posts where author=p_me),'[]'),'ownCommentIDs',coalesce((select jsonb_agg(id) from social_private.comments where author=p_me),'[]'),'ownMessageIDs',coalesce((select jsonb_agg(id) from social_private.messages where author=p_me),'[]'),
 'attachments',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'kind',a.kind,'mime',a.mime,'size',a.size,'roomID',a.room,'messageID',a.message,'postID',a.post)) from social_private.attachments a where a.ready and ((a.post is not null and social_private.can_read_post(p_me,a.post) and exists(select 1 from social_private.posts pp where pp.id=a.post and not pp.deleted)) or(a.message is not null and social_private.can_read_room(p_me,a.room) and exists(select 1 from social_private.messages mm where mm.id=a.message and not mm.deleted and not social_private.blocked(p_me,mm.author))))),'[]'),
 'organizations',coalesce((select jsonb_agg(jsonb_build_object('id',o.id,'name',o.name,'about',o.about,'status',o.status,'followed',exists(select 1 from social_private.organization_follows where organization=o.id and member=p_me),'canManage',exists(select 1 from social_private.organization_admins where organization=o.id and member=p_me))) from social_private.organizations o where o.status='verified' or exists(select 1 from social_private.organization_admins where organization=o.id and member=p_me)),'[]'),
 'savedEvents',coalesce((select jsonb_agg(event_id) from social_private.saved_events where member=p_me),'[]')) into result from social_private.members me where me.id=p_me;
 return result;
end $$;

